canales-de-discord:
  commands: ''
  ban: ''
  login: ''
  console: ''
  chat-bridge: ''
  join-and-leave: ''
  system: ''
expiration-session: 1000
level-moderation-chat: 0.0
purge-tag-range: 0
check-ban-by-ip: false
server-mode: mix_mode
chace-dupe-frame: 0.5
password-ssl: ''
active-time: 192309610
roof-nether: true
checker:
  RoofNether: false
  AntiIlegal: true
  AntiIlegalBlock: true
  AntiIlegalItem: true
  AntiOP: false
  AntiArmament: false
  AntiDupe: true
mysql:
  username: ''
  password: ''
  host: ''
  port: ''
  database: ''
token-bot: ''
email:
  password: ''
  name: ''
